### ISSUE TITLE
Add error message when trying to generate a statement containing a type that is not included

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/contractsgenerator-dart#13]
Consider:

```cs
namespace A {
    class Dto {}
}

namespace B {
   class Dto { A.Dto Something { get; set; } }
}
```

And a config of:

```yaml
include: B\..*
```

Contract generation will fail with an exception without any info what went wrong. Provide an error message explaining the situation.

**Comment by jakubfijalkowski** [comment]
Let's leave it to a server generator. I have a plan to include a number of checks there, one of which is for situations like this one.
