### ISSUE TITLE
`Generator script failed with:` and no error message when `dotnet` is not in `$PATH`

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/contractsgenerator-dart#24]
Today I got the following error when trying to generate contracts 

```bash
$ dart run contracts_generator
Generator script failed with:
```
and exits with code 1.

The project setup is not complete, so possible causes could be:
1. `contracts_generator.yaml` is not configured correctly (e.g wrong paths in `input.project`)
2. `contracts-config.json` file is not configured correctly or does not exist (same thing happens in both cases).

I think there should be more logs to help debug the cause.

**Comment by bartekpacia** [comment]
I uninstalled `dotnet` _formula_ from Homebrew and followed advices in [this README](https://github.com/leancodepl/contractsgenerator-dart/tree/feature/generator-alpha6#prerequisites) to make it work.

Also interesting:
When `dotnet` is not installed/not in $PATH, this issue happens as well. Some error message should be added to handle this case.

**Comment by Saancreed** [comment]
The server bootstrap script is supposed to [notify about this](https://github.com/leancodepl/contractsgenerator/blob/26032b6fb2bef30ad9e6eb8ab8a02bda70119745/tools/generate.sh#L31-L40). Maybe `dart run contracts_generator` somehow consumes stderr by itself so that message is not displayed to the user? Does the `Generator script failed with:` message come from stdout or stderr?

**Comment by shilangyu** [comment]
Its related to the old generator bug where it would send its errors to stdout instead of stderr (C#, not the script), so I was forwarding only stdout. I have already fixed this so it's just waiting for a merge.

**Comment by bartekpacia** [comment]
> I have already fixed this so it's just waiting for a merge.

@shilangyu is this merged?

**Comment by shilangyu** [comment]
No it is not and probably will not be soon. Unfortunately this was released in a c# generator version that also includes a pretty big breaking change which I did not have time to implement. I can release a temporary hotfix for this if needed.

**Comment by bartekpacia** [comment]
No need to rush, I just thought we might've forgotten to close this issue.
