### ISSUE TITLE
Use `json_serializable`'s enum serde

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/contractsgenerator-dart#29]
In 6.0.0 `json_serializable` added enum serde. Use it instead of generating own serde.

**Comment by shilangyu** [comment]
Not helpful in usercode.

**Comment by bartekpacia** [comment]
what's _enum serde_ in Dart & `package:json_serializable` context?

**Comment by shilangyu** [comment]
`package:json_serializable` added some enum serialization (https://pub.dev/packages/json_serializable/changelog#600). This issue was about taking advantage of it in the generator, but in the end it looks like we can't really take advantage of it.
